---
# tasks file for install-nodejs

- getent:
    database: passwd
    key: "{{ user_to_install }}"
    split: ":"

- set_fact:
    user_to_install_home: "{{ getent_passwd[user_to_install][4] }}"  

- debug:
    msg: "home: {{ user_to_install_home }}"

- name: Creates directory
  file: 
    path: "{{ user_to_install_home }}/.local/install/node" 
    state: directory
    owner:  "{{ user_to_install }}"
  become: yes  

- name: downloading {{ url_path }}/{{ file_name }}.tar.xz with checksum check
  get_url:
    url: "{{ url_path }}/{{ file_name }}.tar.xz"
    dest: "/tmp/{{ file_name }}.tar.xz"
    checksum: "{{ file_checksum }}"

# - name: Extract node.tar.xz into 
#   unarchive:
#     src: "/tmp/{{ file_name }}.tar.xz"
#     dest: '/tmp/ans'
#   become: yes
#     #dest: "{{ user_to_install_home }}/.local/install/node"

